title: []
logo: ./assets/img/standing_photo.jpg
email: aosmani203004 at bscse dot uiu dot ac dot bd
description: Undergraduate Student, Department of Computer Science and Engineering, United International University
show_downloads: false
google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: CV
    icon: <i class="fa-solid fa-file"></i>
    link: ./assets/docs/MyResume.pdf
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AOAOcb0i-jIJLZgUrqkQJ9lU5GzGXF63xjaaiOfEX7N-vS3EXr_Ape524FkLDk2ELw8ZFRhZ4-K--TB7jUvgOA&user=CewWo2IAAAAJ
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/AnasIshfaque
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/anas-mohammad-ishfaqul-muktadir-osmani-721a55237/
  # - name: Blog
  #   icon: <i class="fa-solid fa-pen"></i>
  #   link: https://www.bodunhu.com/blog/

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
